# Generated by Django 4.2.30 on 2026-09-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alert_config', serialize=False, to='machines.machine')),
                ('max_temperature', models.FloatField(default=75.0)),
                ('max_vibration', models.FloatField(default=0.05)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
