# ingestion-worker/src/main/resources/application.properties

server.port=8081

spring.application.name=ingestion-worker
spring.datasource.url=jdbc:postgresql://localhost:5433/telemetry_db
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.integration.jdbc.initialize-schema=never

mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=java_ingestion_worker
mqtt.topic=telemetry/v1/data
mqtt.batch-size=10